### ISSUE TITLE
ログイン時に名前が0であるとログインできない問題

### ISSUE THREAD

**Issue by akarregi** [kiridaruma/Onset#13]
課題 #12 と関連しています。

js/script.js : 16 - 19

``` js
    if(nick == '' || pass == '' || room == undefined){
        $('#enterNotice').text('空欄があります');
        return;
    }
```

恐らくこの辺りのコードで、`0`が空として評価されるためログインできません。

**Comment by akarregi** [comment]
login.php: 10

``` php
    if(!$nick || !$pass || !$room) throw new Exception('空欄があります');
```

ここが原因かもしれません。エラー文が同一なので...

**Comment by kiridaruma** [comment]
暗黙の型変換でやられてますねー...  
修正は簡単なので、治しておきます

**Comment by kiridaruma** [comment]
修正して、masterに反映させておきました  
これも比較的軽微(部屋名とか名前に0って入れる人そんなにいませんよね...?)なので、サイレントアップデートとしておきます
