### ISSUE TITLE
部屋が見つからないバグ

### ISSUE THREAD

**Issue by taniko** [kiridaruma/Onset#16]
ログイン及び部屋の削除をする際に部屋が見つからないバグがありました.
<test> といった部屋名などを登録した時に発生しました.

`Onset::getRoomlist()`で得られる配列の添字はエスケープ処理済みですが, `$room`はエスケープ処理がされていないため, `if(!isset($roomlist[$room]))` でtrueになり例外が発生しているようです.

以下の2つを修正すればいいかと思います
- Onset/src/login.php
- Onset/src/removeRoom.php

**Comment by kiridaruma** [comment]
指摘ありがとうございます  
$_POSTから値を取り出す際にhtmlspecialchars()を当てるように修正しました
