### ISSUE TITLE
ディレクトリ構成の変更

### ISSUE THREAD

**Issue by yumiji3156** [kiridaruma/Onset#17]
インストールマニュアルを作っていて生じた問題として提起。

/home/username% git clone ****
↓
Onset/Onet/本体
Onset/room/ セーブデータ

cp Onset/Onset www/
Cp Onset/room ./
とすることで、
http://username.saklura.ne.jp/Onset/
でアクセスが可能となります。

が、src/config.phpとroomのパスが、
../../../room
となります。
デフォルトでは、
../../room
なので、configの修正が必要になります。

www上にてgit cloneしてしまえば、
username.sakura.ne.jp/Onset/Onset
というアドレスでアクセスすることは可能となりますが、
wwwより上の階層にroomを置き、
www直下では無く、Onsetディレクトリの中にOnset.phpを入れることが設置上望ましいです。

なので、ディレクトリ構成を、どどんとふに倣い、
Onset/public_htmlOnet/本体
Onset/room/ セーブデータ
とすることを提案します。
これならば、configを弄ること無く設置ができます。

**Comment by kiridaruma** [comment]
なるほど、ファイル構成変えるだけでも設置しやすくなりますね  
やっておきます

**Comment by kiridaruma** [comment]
ファイル構成の変更を行いました  
システムや機能的には何の変更もないので、このコミットもサイレントアップデートとしておきます

**Comment by yumiji3156** [comment]
ありがとうございます。
明日の夜、マニュアル作れると思います。
