### ISSUE TITLE
セーブデータのディレクトリ構成について

### ISSUE THREAD

**Issue by daicyan** [kiridaruma/Onset#2]
いくつか、セキュリティ上の懸念がありそうな点についての機能改善です。

・roomディレクトリが、'../room'にハードコーディングされていますが、カスタマイズできるようにした上で、documentroot以外の場所に配置するようにしてほしい。
.htaccessはレンタルサーバーやHTTPサーバーによっては使えない場合があるため、.htaccessのセキュリティ設定に依存すべきではない。

・部屋名ディレクトリが、部屋名そのものになっているため、インジェクション攻撃に対して脆弱なため、部屋名の文字列をエスケープするか、エンコードした部屋名をディレクトリ名にする。

**Comment by kiridaruma** [comment]
ありがとうございますー
一つ目に関しては、configファイル等を置いて対処してみます
二つ目は、ディレクトリ名を直接部屋名として使うのではなく、json等で部屋名やディレクトリ名を管理する形にして対処しようと思います

あと、Twitterのほうで言ってくださった「スケールしにくい」の件ですが、その手の知識があまり無いので現状は様子を見ます

**Comment by daicyan** [comment]
あと、全体的にコード内にMagicNumberが多すぎるように思いますので、書き込み行数の上限、部屋名や書き込み文字数や名前の最大長、各種ディレクトリパス、ログアウト後の飛び先URLなどもconfigや定数管理用ファイルなどで別出しにしたほうがメンテナンス性は向上します。
json等で管理するようにするのであれば、ディレクトリ名なんかはuuidにしてしまえば、ハッシュと違って衝突が起きないので、実装は簡単になると思います。
あと、login時のセッションIDをmt_randで生成していますが、衝突する可能性があるので、こちらもmt_randより負荷は高くなりますが、どうせログイン時一度しか呼び出されないのでuuidを使ったほうがいいと思います。
スケールの点については、「ここは利用者増えたらボトルネックになるだろうな」という漠然と思う箇所がいくつかあるだけなので、もう少し考えをまとめてみます。
