### ISSUE TITLE
config.php の処理関係で気になったこと

### ISSUE THREAD

**Issue by akarregi** [kiridaruma/Onset#21]
要約:
- `config.php` をいちいち一つのファイルとしてロードするのは保守性に欠けるからどうにか
- `$config["CONFNAME"]`よりは`Onset::CONFNAME`の方がいいと思う
## 1. ロード問題

``` php
// とあるコード
require_once('core.php');
require_once('config.php');
```

 `config.php`を一つのファイルとして読み込んでいるので、行が増える、**ロードしてなくて`$config`が使えない**などという問題があります。

解決方法: `core.php`の段階で読みこめば大丈夫かと思います。
## 2. $config

個人的主観)です。
`$config["CONFNAME"]`が地味に長くて取っ付きづらいので、`Onset::CONFNAME`のように定数にするべきです。

解決方法: クラス化(e.g. OnsetConf)してやって定数化

**Comment by kiridaruma** [comment]
1に関しては、ちょっと見直してみます
外部ライブラリ等をcomposer使って導入するとして、どこからrequireするか等重要になると思うので、次のアップデートでいじってみます

2に関しては、Class::Configとすると設定を書くときに面倒(classの{}の中にconfigの値を書き込むのは違和感)なので、ちょっと見送りですかね

ありがとうございますー

**Comment by akarregi** [comment]
`$config`については、**関数使用時にグローバル宣言必須**という点を追記しておきます...

**Comment by akarregi** [comment]
更に追記します。
**現行の core.php ですでに config.php は読み込まれている**みたいです...なんてこった...。

core.php: 2

``` php
require_once(dirname(__FILE__).'/config.php');
```

**Comment by kiridaruma** [comment]
あー、クラスだとグローバル宣言無しで行けますもんね...
今のところの案としては、コンフィグをクラス化してArrayAccessを継承させて無理やり配列形式でアクセスしようかなぁと考えています

**Comment by akarregi** [comment]
うーん、単純に`const`で定数にすればいいと思います。
いかがでしょうか。

**Comment by kiridaruma** [comment]
コミット10dbd6d7751fdd0ca4b1eff37828a42b43898f56にて解決しました
