### ISSUE TITLE
json返却時にMIMEが指定されていない問題

### ISSUE THREAD

**Issue by akarregi** [kiridaruma/Onset#22]
JSONを返却するときにMIMEが指定されていません。
JSONのMIMEはRFC 4627により **application/json** にする必要があります。

また、 `removeRoom.php`にcurlを投げてみたところ、MIMEは **text/html** のようです。
この場合だと、「JSONの直接ブラウジングによるXSS」の危険性があります(下記参考より引用)。

追記例: 

``` php
header('content-type: application/json; charset=utf-8');
```

参考: [PHPで値を JSON 形式で表示したい場合、 header('content-type: application/json;')は必要？](http://ja.stackoverflow.com/questions/12753/phpで値を-json-形式で表示したい場合-headercontent-type-application-jsonは必要)

**Comment by kiridaruma** [comment]
あー、Content-Typeはちゃんと指定しておきます
指摘ありがとうございますー

**Comment by kiridaruma** [comment]
コミット150cb623d309351f18af87a93c89387b97e8218eにて解決しました
