### ISSUE TITLE
BCDice の git submodule 化

### ISSUE THREAD

**Issue by akarregi** [kiridaruma/Onset#28]
BCDice の容量が半端ないのとアップデートが面倒くさいです。
なので、いっそ`git submodule`で読みこむようにすればいい感じになると考えられます。

**Comment by kiridaruma** [comment]
submoduleがいまいちわかってないので、調べてやってみます
ありがとうございますー

**Comment by kiridaruma** [comment]
ver2.1.0でsubmodule化しました
