### ISSUE TITLE
部屋の削除が出来ない

### ISSUE THREAD

**Issue by daicyan** [kiridaruma/Onset#4]
部屋の削除を実施しようとしたら、InternalServerエラーが出ます。
エラーログとdeleteRoom.phpを参照した限りでは、core.php内にisSetRoomAndNameがないからではないでしょうか？

**Comment by kiridaruma** [comment]
指摘ありがとうございます
対処しました

**Comment by daicyan** [comment]
素早い対応ありがとうございます。無事動作確認しました。
