### ISSUE TITLE
Apacheにおいて、BCDice動作のための設定の必要性

### ISSUE THREAD

**Issue by akarregi** [kiridaruma/Onset#6]
**私の環境だけの問題かもしれません。細かい調査が必要です。**

Onset! と BCDice を連携するにあたり、rubyのCGI設定が必要です。
具体的には、`ExecCGI`と`AddHandler`の設定、`roll.rb`, `bcdiceCore.rb`のENV設定の変更です。

この辺りを何処かに明記しておかないと、新規導入する方が困る可能性があるのでイシューを建てます。

**Comment by kiridaruma** [comment]
導入解説ページを[blog](https://blog.kiridaruma.net)に書いておきます  
指摘ありがとうございますー
